# output settings
channel_input : 50
dim_input     : 512
# model settings
model_type      : "vit_b"
device          : "cuda"

# Model hyperparameters
points_per_side                 : 50
pred_iou_thresh                 : 0.5
stability_score_thresh          : 0.8
crop_n_layers                   : 1
crop_n_points_downscale_factor  : 2
min_mask_region_area            : 5000 

